# Generated by Django 3.0.6 on 2020-06-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200609_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='rubric',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
