# Generated by Django 3.0.6 on 2020-06-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200609_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(default='account/img/user_default.png', null=True, upload_to='artucle_img'),
        ),
    ]
